### ISSUE TITLE
Error with get_pairs_title_from_nondup.py

### ISSUE THREAD

**Issue by carolinasisco** [chjiao/PEHaplo#15]
Hello, I´m having an error when PEHaplo runs get_pairs_title_from_nondup.py. It exits with non zero status.

I have installed Networkx version 1.11
My reads names are CP1p_1.fa and CP1p_2.fa

Can you guide me through to the solution?

Thanks!

**Comment by chjiao** [comment]
Can you paste the error information here please?

**Comment by carolinasisco** [comment]
Hi, Thank you for your reply, the error I got is:

Traceback (most recent call last):
  File "/home/geninfo/msisco/TAR-VIR/PEHaplo/tools/get_pairs_title_from_nondup.py", line 26, in <module>
    assert (title_dict[base].endswith('1') and title.endswith('2')) or (title_dict[base].endswith('2') and title.endswith('1'))
AssertionError
Traceback (most recent call last):
  File "pehaplo.py", line 157, in <module>
    main()
  File "pehaplo.py", line 84, in main
    subprocess.check_call('python "%s"/tools/get_pairs_title_from_nondup.py kept_num.fa kept_pairs.txt' % base_path, shell=True)
  File "/home/geninfo/msisco/miniconda3/envs/pehaplo/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python "/home/geninfo/msisco/TAR-VIR/PEHaplo"/tools/get_pairs_title_from_nondup.py kept_num.fa kept_pairs.txt' returned non-zero exit status 1

My reads are named are cp_1.fa and cp_2.fa

The list of packages installed in my environment, where PEHaplo was installed:

libzlib                   1.2.11            h166bdaf_1014    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
networkx                  1.11                     pypi_0    pypi
numpy                     1.12.1          py27_blas_openblas_200  [blas_openblas]  conda-forge
openblas                  0.2.19                        2    conda-forge
openssl                   1.1.1o               h166bdaf_0    conda-forge
overlap_extension         2.0                  h6bb024c_1    kennethshang
pango                     1.42.4               h69149e4_5    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pygraphviz                1.3.1                    py27_0    bioconda
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
samtools                  1.15.1               h1170115_0    bioconda
scipy                     0.18.1          np112py27_blas_openblas_201  [blas_openblas]  conda-forge
setuptools                44.0.0                   py27_0    conda-forge
sga                       0.10.13                       0    bioconda
sqlite                    3.38.3               h4ff8645_0    conda-forge
tbb                       2020.2               h4bd325d_4    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxpm               3.5.13               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxt                1.2.1                h7f98852_2    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge

Again, Thanks!

**Comment by carolinasisco** [comment]
Hi, 

I changed the format of my reads, they now have this header:

@VH00487_AAAL233M5:1:1101:32774:1038#0/1
CTAGAGGAGCTACTGTAGTAATTGGAACAAGCAAATTCTATGGTGGTTGGCACAACATGTTAAAAACTGTTTATAGTGATGTAG

@VH00487_AAAL233M5:1:1101:32774:1038#0/2
CTAGAGGAGCTACTGTAGTAATTGGAACAAGCAAATTCTATGGTGGTTGGCACAACATGTTAAAAACTGTTTATAGTGATGTAG

But now I´m having this error:

Error Correction Finished

Traceback (most recent call last):
  File "/home/geninfo/msisco/TAR-VIR/PEHaplo/tools/join_pair_end_fasta.py", line 19, in <module>
    f_out.write(title1+'\n'+seq1+'\n'+title2+'\n'+seq2+'\n')
NameError: name 'title1' is not defined
Traceback (most recent call last):
  File "pehaplo.py", line 157, in <module>
    main()
  File "pehaplo.py", line 55, in main
    subprocess.check_call('python "%s"/tools/join_pair_end_fasta.py karect_%s karect_%s karect_whole.fa' % (base_path, fa1_file, fa2_file), shell=True)
  File "/home/geninfo/msisco/miniconda3/envs/pehaplo/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'python "/home/geninfo/msisco/TAR-VIR/PEHaplo"/tools/join_pair_end_fasta.py karect_CP1_1.fasta karect_CP1_2.fasta karect_whole.fa' returned non-zero exit status 1

What could be happening?

**Comment by chjiao** [comment]
The script assumes that the fasta file title starts with ">", while in your data, the title starts with "@". Please reformat your data and run the tool again.

**Comment by carolinasisco** [comment]
Hi, thank you for your reply. I have changed the format of my reads, however I got the following error:

Size of File:0
Number of Strings: K 0
Size of strings:0
Creating tree:
User Time for Constructing tree with no sorting required: 0 ms
Segmentation fault
The nodes of the whole graph is: 0; the edges of the whole graph is: 0.
index: input file is empty
Traceback (most recent call last):
  File "pehaplo.py", line 157, in <module>
    main()
  File "pehaplo.py", line 99, in main
    subprocess.check_call('sga index -t %s Contigs.fa' % args.threads, shell=True)
  File "/home/geninfo/msisco/miniconda3/envs/pehaplo/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'sga index -t 18 Contigs.fa' returned non-zero exit status 1

**Comment by chjiao** [comment]
Hi, looks like the `sga` command get an empty input file (`Contigs.fa`), you can check if you have the middle file `kept_num.fa`, if this file is not empty, probably reduce your overlap threshold.

**Comment by carolinasisco** [comment]
Hi, thanks. I can confirm that Contigs.fa is empty, however, kept_num.fa is not. Currently my command line looks like this:
python pehaplo.py -f1 cp_1.fa -f2 cp_2.fa -l 180 -r 150 -l1 180 -F 375 --threads 18
Should I reduce -l and -l1?

**Comment by carolinasisco** [comment]
Hello, I was able to run PeHaplo, reducing the overlap threshold works. 
At the end it just shows a message saying  "rm: cannot remove 'index': No such file or directory", but the file Contigs.fa has the final assembly, so it´s just a cleaning step.
